#!/usr/bin/env php
<?php
/**
 * Script used to determine merges between branches
 * All OSX computers have PHP, so use PHP!
 */

// Require Configuration
$config = require __DIR__ . '/config/config.php';
if (!$config) {
    throw new Exception('Config missing!');
}

$notifySlack = $config['slack']['active'];

// Get command line options
$options = getopt('', ['test']);
if (isset($options['test']) && $options['test'] === false) {
    $notifySlack = false;

    unset($argv[array_search('--test', $argv)]);
    $argv = array_values($argv);
}

////////////////////////////////////////////////////
// Processing
////////////////////////////////////////////////////

/**
 * Output message
 * @var string
 */
$message = '';

/**
 * Determine BaseDir (use config, or local)
 */
$currentDir = getcwd();
$gitStatus = 0;
$gitResult = [];
exec("git -C {$currentDir} rev-parse > /dev/null 2>&1", $gitResult, $gitStatus);

if ($gitStatus === 0) {
    $baseDir = $currentDir;
} elseif (isset($config['git']['base_dir'])) {
    $baseDir = $config['git']['base_dir'];
} else {
    error_log("Current directory is not a GIT directory and no git.base_dir is set in config, exiting.");
    exit;
}

/**
 * Accept arguments as the Git hashes to use to determine merged branches
 */
if (!empty($argv[1]) && !empty($argv[2])) {
    $output = [
        $argv[1],
        $argv[2],
    ];
} else {
    /**
     * Command Line Magic
     * Determine previous two tags beginning with 'prod-' and get the list of branches
     * merged (into master) between them. Then pull out the GitHub Issue IDs
     */
    exec('git -C ' . $baseDir . ' tags | grep ' . $config['git']['prod_tag_prefix'] . ' | tail -r -2', $output);
}
if (empty($output[0]) || empty($output[1])) {
    error_log("No hashes found, exiting.");
    exit;
}

exec('git -C ' . $baseDir . ' log --merges --grep="Merge pull request" --pretty=format:"%s" ' . "{$output[0]}...{$output[1]}", $result);
echo "Executing for: {$baseDir}" . PHP_EOL;
echo "Determining merged PRs between the following hashes: {$output[0]} {$output[1]}" . PHP_EOL . PHP_EOL;

/**
 * Iterate through Shell Output and create array of the matching GitHub Issues IDs
 */
$issueList = [];
foreach ($result as $mergedPr) {
    preg_match('/#([0-9]+)/', $mergedPr, $matches);
    if (!empty($matches[1])) {
        array_push($issueList, $matches[1]);
    }
}
asort($issueList);

if (empty($issueList)) {
    error_log("No Github issues found between {$output[0]}...{$output[1]}");
    exit;
}

/**
 * Call GitHub API and iterate through issues listed above in order to get
 * PR contents to determine inclusion of JIRA issues for the WEB Repo
 */
$message = "Merged PRs between the following hashes: {$output[0]} {$output[1]}" . PHP_EOL;
foreach ($issueList as $issueId) {
    $issueInfo = '';

    $url = implode('/', [
        $config['github']['api_host'],
        $config['github']['api_request_base'],
        $config['github']['organization'],
        $repository,
        $config['github']['api_issues_path'],
        $issueId
    ]);

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Authorization: token ' . $config['github']['user_api_key'],
        'User-Agent: ' . $config['github']['user_agent']
    ]);
    $curlResult = curl_exec($ch);
    $result = json_decode($curlResult, true);

    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    if ($httpCode !== 200) {
        error_log('ERROR, invalid response received from GitHub, aborting for this issue:' . $issueId);
        continue;
    }

    $gitHubIssueId     = $result['number'];
    $gitHubIssueDesc   = $result['body'];
    $gitHubIssueTitle  = $result['title'];
    $gitHubIssueAuthor = $result['user']['login'];

    // Deterine appropriate URLs to show (JIRA if available, default GH)
    $jiraUrl = '';

    $url = implode('/', [
        $config['github']['web_host'],
        $config['github']['organization'],
        $repository,
        $config['github']['web_pr_path'],
        substr($gitHubIssueId, 0)
    ]);

    // Check for JIRA Link in the form of PROJECT-ISSUEID
    $matches = [];
    preg_match('/([A-Za-z]+\-[0-9]+)/', $result['body'], $matches);
    if (count($matches) > 0) {
        $jiraUrl = $config['jira']['base_url'] . $matches[0];
    }

    // GitHub Data
    $githubUser = $result['user']['login'];

    // Flow User Name
    $userMention = array_key_exists($githubUser, $config['slack']['user_map'])
        ? $config['slack']['user_map'][$githubUser] : $githubUser;
    $outputUrl = !empty($jiraUrl) ? $jiraUrl : $url;

    // Determine issue
    $issueInfo  = "#{$result['number']} (@{$userMention}): {$result['title']} ({$outputUrl})";
    $message .=  "  " . $issueInfo . PHP_EOL;
}

echo $message;

if ($notifySlack && !empty($config['slack']['webhook_url'])) {
    notifySlack($config, stringToCodeBlock($message));
}

function stringToCodeBlock($message)
{
    $message = "```{$message}```";
    return $message;
}

function notifySlack(array $config, $message)
{
    // only one channel for now
    $channel = $config['slack']['channels'][0];

    $postFields = [
        'text'       => $message,
        'channel'    => $channel,
        'username'   => $config['slack']['username'],
        'icon_emoji' => $config['slack']['icon_emoji'],
    ];

    $payload = json_encode($postFields);

    $ch = curl_init($config['slack']['webhook_url']);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($ch, CURLOPT_POSTFIELDS,  $payload);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Content-Type: application/json',
        'Content-Length: ' . strlen($payload)
    ]);
    $curlResult = curl_exec($ch);
    $result = json_decode($curlResult, true);

    echo 'CURL Result: ' . $curlResult . PHP_EOL;
}

