#!/usr/bin/env php
<?php
/**
 * Script used to determine merges between branches
 * All OSX computers have PHP, so use PHP!
 */

// Require Configuration
$config = json_decode(file_get_contents('config.json'), true);
if (!$config) {
    throw new Exception('config.json file missing!');
}

/**
 * Output message
 * @var string
 */
$message = '';

/**
 * Accept arguments as the Git hashes to use to determine merged branches
 */
if ($argv[1] && $argv[2]) {
    $output = [
        $argv[1],
        $argv[2],
    ];
} else {
    /**
     * Command Line Magic
     * Determine previous two tags beginning with 'prod-' and get the list of branches
     * merged (into master) between them. Then pull out the GitHub Issue IDs
     */
    exec('cd ' . $config['git']['base_dir'] . ' && git tags | grep ' . $config['git']['prod_tag_prefix'] . ' | tail -r -2', $output);
}
exec('cd ' . $config['git']['base_dir'] . ' && git log --merges --grep="Merge pull request" --pretty=format:"%s" ' . "{$output[0]}...{$output[1]}", $result);
echo "Determining merged branches between the following hashes: {$output[0]} {$output[1]}" . PHP_EOL . PHP_EOL;

/**
 * Iterate through Shell Output and create array of the matching GitHub Issues IDs
 */
$issueList = [];
foreach ($result as $mergedPr) {
    preg_match('/#([0-9]+)/', $mergedPr, $matches);
    if (!empty($matches[1])) {
        array_push($issueList, $matches[1]);
    }
}
asort($issueList);

if (empty($issueList)) {
    error_log("No Github issues found between {$output[0]}...{$output[1]}");
    exit;
}

/**
 * Call GitHub API and iterate through issues listed above in order to get
 * PR contents to determine inclusion of JIRA issues for the WEB Repo
 */
$message = "Merged PRs between the following hashes: {$output[0]} {$output[1]}" . PHP_EOL;
foreach ($issueList as $issueId) {
    $issueInfo = '';
    $url = $config['github']['api_host'] . $config['github']['api_request_path'] . '/' . $issueId;

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Authorization: token ' . $config['github']['user_api_key'],
        'User-Agent: ' . $config['github']['user_agent']
    ]);
    $curlResult = curl_exec($ch);
    $result = json_decode($curlResult, true);

    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    if ($httpCode !== 200) {
        error_log('ERROR, invalid response received from GitHub, aborting for this issue:' . $issueId);
        continue;
    }

    $gitHubIssueId     = $result['number'];
    $gitHubIssueDesc   = $result['body'];
    $gitHubIssueTitle  = $result['title'];
    $gitHubIssueAuthor = $result['user']['login'];

    // Deterine appropriate URLs to show (JIRA if available, default GH)
    $jiraUrl = '';
    $url = $config['github']['pr_path'] . substr($gitHubIssueId, 0);

    // Check for JIRA Link
    $matches = [];
    preg_match('/(' . $config['jira']['project'] . '\-[0-9]+)/', $result['body'], $matches);
    if (count($matches) > 0) {
        $jiraUrl = $config['jira']['url'] . $matches[0];
    }

    // GitHub Data
    $githubUser = $result['user']['login'];

    // Flow User Name
    $userMention = array_key_exists($githubUser, $config['slack']['users'])
        ? $config['slack']['users'][$githubUser] : $githubUser;
    $outputUrl = !empty($jiraUrl) ? $jiraUrl : $url;

    // Determine issue
    $issueInfo  = "#{$result['number']} (@{$userMention}): {$result['title']} ({$outputUrl})";
    $message .=  "  " . $issueInfo . PHP_EOL;
}

echo $message;

if (!empty($config['slack']['notify']['webhook_url'])) {
    notifySlack($config, stringToCodeBlock($message));
}

function stringToCodeBlock($message)
{
    $message = "```{$message}```";
    return $message;
}

function notifySlack(array $config, $message)
{
    $postFields = [
        'text'       => $message,
        'channel'    => $config['slack']['notify']['channel'],
        'username'   => $config['slack']['notify']['username'],
        'icon_emoji' => $config['slack']['notify']['icon_emoji'],
    ];

    $payload = 'payload=' . json_encode($postFields);

    $ch = curl_init($config['slack']['notify']['webhook_url']);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_setopt($ch, CURLOPT_POSTFIELDS,  $payload);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $curlResult = curl_exec($ch);
    $result = json_decode($curlResult, true);

    var_dump($curlResult);
}

